### ISSUE TITLE
Couldn't load plugin 'rasterisochrones' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by seizethedata** [Anaphory/qgis-raster-isochrones#1]
Hi there @Anaphory! Thanks for developing the plugin. 

I have trouble running it, QGIS throws an error:

```
Couldn't load plugin 'rasterisochrones' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'osr' 

Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/dnaiel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/rasterisochrones/__init__.py", line 35, in classFactory
    from .rasterisochrones import RasterIsochrones
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/dnaiel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/rasterisochrones/rasterisochrones.py", line 50, in 
    import osr
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'osr'
```

Can you suggest the workarounds for this? 
Thanks.

**Comment by Anaphory** [comment]
I am not much involved with this kind of development any more, so it might take an indefinitely long time until I actually look at the issue and can provide a proper fix.

I forget where QGis pulls its python environment from. My first attempt would be to try insisting the `osr` package in there, or to try to remember where python dependencies ate declared in the plugin metadata and add it there.

**Comment by seizethedata** [comment]
Got it, thanks for the suggestions
